version: '3.8'

services:
  database:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movies_db
      MYSQL_USER: springuser
      MYSQL_PASSWORD: ThePassword
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql